packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - core-js-pure

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - msw
  - sharp
  - workerd

overrides:
  "eslint@^9": "9.38.0"
