name: "Docker Build & Push"
description: "Builds and pushes the Docker image with optional caching"

inputs:
  version:
    required: true
    description: "Version tag for the Docker image"
  tag_latest:
    required: false
    default: "false"
    description: "Tag the image as latest"
  tag_latest_dev:
    required: false
    default: "false"
    description: "Tag the image as latest-dev"
  push:
    required: false
    default: "true"
  turbo_token:
    required: true
    description: "Turborepo token for remote cache authentication"
  turbo_api:
    required: true
    description: "API endpoint for Turborepo remote cache"
  turbo_team:
    required: true
    description: "Team name for Turborepo remote cache"
  github_token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Cache pnpm
      uses: actions/cache@v4
      id: pnpm-cache
      with:
        path: pnpm-store
        key: pnpm-cache-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Inject cache into Docker
      uses: reproducible-containers/buildkit-cache-dance@v3.2.0
      with:
        cache-map: |
          {
            "pnpm-store": "/pnpm-store"
          }
        skip-extraction: ${{ steps.pnpm-cache.outputs.cache-hit }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: apps/api/Dockerfile
        push: ${{ inputs.push }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}-api:cache
        cache-to: type=inline
        secrets: |
          TURBO_TOKEN=${{ inputs.turbo_token }}
        build-args: |
          VERSION=${{ inputs.version }}
          TURBO_API=${{ inputs.turbo_api }}
          TURBO_TEAM=${{ inputs.turbo_team }}
          PNPM_STORE=/pnpm-store
        tags: |
          ${{ inputs.tag_latest == 'true' && format('ghcr.io/{0}-api:latest', github.repository) || '' }}
          ${{ inputs.tag_latest_dev == 'true' && format('ghcr.io/{0}-api:latest-dev', github.repository) || '' }}
          ghcr.io/${{ github.repository }}-api:${{ inputs.version }}
          ghcr.io/${{ github.repository }}-api:cache
