name: CI - API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Build, lint, and Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "./package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: TypeScript build check
        working-directory: apps/api
        run: npm run build

      - name: Lint
        working-directory: apps/api
        run: npm run lint

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:apps/api"
          push: false
          build-args: |
            VERSION=${{ github.event.release.tag_name }}
