name: CI - Full repo

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI - Full repo
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Cache nextjs output
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/apps/web/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}-${{ hashFiles('apps/web/**/*.{js,jsx,ts,tsx}') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}-

      - name: Install dependencies
        run: npm install --global turbo && npm ci

      - name: Build
        run: turbo run ci

      - name: Lint
        run: turbo lint

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/api/Dockerfile
          push: false
          cache-from: type=registry,ref=ghcr.io/${{ env.IMAGE_NAME }}:cache
          cache-to: type=inline
          build-args: |
            VERSION=${{ github.event.release.tag_name }}
