name: CI

on:
  pull_request:
    branches:
      - main

env:
  TURBO_API: ${{ vars.TURBO_API }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  IMAGE_NAME: ghcr.io/${{ github.repository }}-api
  VERSION: ${{ github.sha }}
  TURBO_SCM_BASE: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
  PNPM_STORE: "/pnpm-store"

jobs:
  monorepo:
    name: Build monorepo
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.10.0

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpx turbo run ci --affected

      - name: Lint
        run: pnpm lint:md && pnpx turbo lint --affected

  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changed Dockerfile
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          since_last_remote_commit: true
          files_yaml: |
            dockerfile:
              - apps/api/Dockerfile
              - apps/api/.dockerignore
              - .github/workflows/ci.yaml

      - name: Skip if Dockerfiles unchanged
        if: steps.changed-files.outputs.dockerfile_any_changed != 'true'
        run: echo "No Dockerfile changes, skipping build."

      - name: Docker build (CI only, no push)
        if: steps.changed-files.outputs.dockerfile_any_changed == 'true'
        uses: ./.github/actions/docker-build
        with:
          version: dev
          env: dev
          push: false
          turbo_token: ${{ secrets.TURBO_TOKEN }}
          turbo_api: ${{ vars.TURBO_API }}
          turbo_team: ${{ vars.TURBO_TEAM }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
