name: Deploy - dev

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    environment: dev

    env:
      IMAGE_NAME: ${{ github.repository }}-api
      PNPM_STORE: "/pnpm-store"

    permissions:
      contents: read
      packages: write # needed to push to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract short hash of current commit
        id: vars
        run: echo "VERSION=dev-$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      # This method of caching pnpm files in Docker builds during CI workflows is from
      # https://dev.to/henryjw/caching-pnpm-modules-in-docker-builds-in-github-actions-mj7#implementation
      - name: Cache pnpm
        uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: pnpm-store
          key: pnpm-cache-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Inject cache into Docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.2
        with:
          cache-map: |
            {
              "pnpm-store": "${{ env.PNPM_STORE }}"
            }
          skip-extraction: ${{ steps.pnpm-cache.outputs.cache-hit }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/api/Dockerfile
          push: true
          cache-from: type=registry,ref=ghcr.io/${{ env.IMAGE_NAME }}:cache
          cache-to: type=inline
          secrets: |
            TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}
          build-args: |
            VERSION=${{ env.VERSION }}
            TURBO_API=${{ vars.TURBO_API }}
            TURBO_TEAM=${{ vars.TURBO_TEAM }}
            PNPM_STORE=${{ env.PNPM_STORE }}
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest-dev
            ghcr.io/${{ env.IMAGE_NAME }}:cache

  cloudflare:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: ${{ vars.APP_BASE_URL }}

    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_BASE_URL: ${{ vars.API_BASE_URL }}
      APP_BASE_URL: ${{ vars.APP_BASE_URL }}
      CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      DEPLOY_ENV: ${{ vars.DEPLOY_ENV }}
      AUTH0_AUDIENCE: ${{ vars.AUTH0_AUDIENCE }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_DOMAIN: ${{ vars.AUTH0_DOMAIN }}
      AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.10.0

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      # Prune to just the necessary files for the web build. Result is in ./out.
      - name: Prep for build
        run: pnpx turbo prune --scope=web

      - name: Install dependencies
        working-directory: ./out
        run: pnpm install

      - name: Deploy secrets to Cloudflare
        working-directory: ./out/apps/web
        # Wrangler secret put takes the value as a piped input.
        run: |
          echo "${{ secrets.API_KEY }}" | pnpx wrangler secret put API_KEY --env dev
          echo "${{ secrets.AUTH0_SECRET }}" | pnpx wrangler secret put AUTH0_SECRET --env dev
          echo "${{ secrets.AUTH0_CLIENT_SECRET }}" | pnpx wrangler secret put AUTH0_CLIENT_SECRET --env dev

      - name: Deploy to site to Cloudflare
        working-directory: ./out
        run: pnpx turbo run cf-deploy
