name: Deploy - dev

on:
  workflow_dispatch:

jobs:
  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract short hash of current commit
        id: vars
        run: echo "VERSION=dev-$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV
        shell: bash

      - name: Docker build and push
        uses: ./.github/actions/docker-build
        with:
          version: ${{ env.VERSION }}
          env: dev

  cloudflare:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: ${{ vars.APP_BASE_URL }}
    permissions:
      contents: read

    steps:
      - name: Deploy to Cloudflare
        uses: ./.github/actions/cloudflare-deploy
