name: Deploy - prod

on:
  release:
    types: [published]

jobs:
  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag name
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Docker build & push
        uses: ./.github/actions/docker-build
        with:
          version: ${{ env.VERSION }}
          push: true
          tag_latest: true
          turbo_token: ${{ secrets.TURBO_TOKEN }}
          turbo_api: ${{ vars.TURBO_API }}
          turbo_team: ${{ vars.TURBO_TEAM }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  cloudflare:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: ${{ vars.APP_BASE_URL }}
    permissions:
      contents: read
    steps:
      - name: Deploy to Cloudflare
        uses: ./.github/actions/cloudflare-deploy
        with:
          deploy_env: ${{ vars.DEPLOY_ENV }}
          api_key: ${{ secrets.API_KEY }}
          auth0_secret: ${{ secrets.AUTH0_SECRET }}
          auth0_client_secret: ${{ secrets.AUTH0_CLIENT_SECRET }}
