name: Deploy - prod

on:
  release:
    types: [published]

jobs:
  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag name
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        shell: bash

      - name: Docker Build & Push
        uses: ./.github/actions/docker-build
        with:
          version: ${{ env.VERSION }}
          env: prod

  cloudflare:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: ${{ vars.APP_BASE_URL }}
    permissions:
      contents: read

    steps:
      - name: Deploy to Cloudflare
        uses: ./.github/actions/cloudflare-deploy
