name: Deploy - dev

on:
  workflow_dispatch:

jobs:
  cloudflare:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: ${{ vars.APP_BASE_URL }}
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare
        uses: ./.github/actions/cloudflare-deploy
        with:
          app_base_url: ${{ vars.APP_BASE_URL }}
          auth0_audience: ${{ vars.AUTH0_AUDIENCE }}
          auth0_client_id: ${{ vars.AUTH0_CLIENT_ID }}
          auth0_client_secret: ${{ secrets.AUTH0_CLIENT_SECRET }}
          auth0_domain: ${{ vars.AUTH0_DOMAIN }}
          auth0_secret: ${{ secrets.AUTH0_SECRET }}
          backend_cf_access_client_id: ${{ secrets.BACKEND_CF_ACCESS_CLIENT_ID }}
          backend_cf_access_client_secret: ${{ secrets.BACKEND_CF_ACCESS_CLIENT_SECRET }}
          cloudflare_account_id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare_d1_token: ${{ secrets.CLOUDFLARE_D1_TOKEN }}
          deploy_env: ${{ vars.DEPLOY_ENV }}
